/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 辅助键 (ctrl / shift / alt 中的 0/1/2/3 个) */
export interface ExtraKey {
  ctrl?: boolean
  alt?: boolean
  shift?: boolean
}
/** 组合键情况 (目标键 + 辅助键) */
export interface KeyCombination {
  /** 目标键 (可用值见 mapper 文件) */
  key: string
  /** 辅助键 (ctrl / shift / alt 中的 0/1 个) */
  extra?: 'ctrl' | 'alt' | 'shift'
}
export function helloWorld(): string
export class KeyboardController {
  constructor()
  /**
   * 模拟目标按键
   * `key` 目标键 (可用值见 mapper 文件)
   * `extra` 辅助键 (ctrl / shift / alt 中的 0/1/2/3 个)
   */
  simulate(key: string, extra?: ExtraKey | undefined | null): void
  /** 监听目标 */
  listen(channel: KeyCombination, executor: (...args: any[]) => any): void
}
